### ISSUE TITLE
Syllabus for FDAC 2024

### ISSUE THREAD

**Issue by harshvardhaniimi** [fdac24/news#1]
Hello Dr. Mockus:
The current link to the syllabus in `news` repo tells us the file [doesn't exist](https://github.com/fdac24/news/blob/main/course.pdf). Can you please update the course syllabus? Thanks!

<img width="1552" alt="Screenshot 2024-08-20 at 4 54 03 PM" src="https://github.com/user-attachments/assets/0a78deb5-56cb-41bc-89f0-0a47ccdc7f2d">

**Comment by audrism** [comment]
Thank you, Added
